userInfo:
  email: tech+aic@mioying.com
  password: Welcome1
  login_url: https://release.miotech.com/
  cookie: 13e02e844f3a80e474d511cab9689c3f78db2766-u=00dfed35-9c46-4b7f-b251-7d4bf56b02ff

wait: 3

drivers:
  chrome: /Users/miotech/opt/chromedriver
  firefox: /Users/miotech/opt/geckodriver

log:
  path: /tmp/logs/
  errPath: /tmp/logs/errors/
  filename: record.log
  screenname: record.png
  filesize: 10
  maxfilenum: 10


workflow:
  url: https://release.miotech.com/workflow/admin/folder


grpc:
  timeout: 350
  pikachu:
    host: 18.182.39.102
    port: 9876
  fi:
    host: 18.182.39.102
    port: 9221
