userInfo:
  email: 
  password: 
  login_url: 
  cookie: 

wait: 3

drivers:
  chrome: chromedriver
  firefox: geckodriver

log:
  path: /tmp/logs/
  errPath: /tmp/logs/errors/
  filename: record.log
  screenname: record.png
  filesize: 10
  maxfilenum: 10


workflow:
  url: 


grpc:
  timeout: 350
  p1:
    host: 
    port: 0
  p2:
    host:
    port: 0
